<?php

namespace App\Services;

use App\Enums\UserRole;
use App\Models\HighUsageFlag;
use App\Models\Notification;
use App\Models\Unit;
use App\Models\User;
use App\Models\WorkOrder;
use App\Models\WorkOrderItem;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Collection;

class FleetNotificationService
{
    public function taskAutoGenerated(WorkOrderItem $item): void
    {
        $item->loadMissing(['workOrder.unit', 'planningItem']);

        $this->notifyRoles([UserRole::PlannerArea], 'task_auto_generated', 'Task maintenance baru', sprintf(
            '%s - %s masuk On Hold dan perlu ditindaklanjuti.',
            $item->workOrder->unit?->current_plate ?? 'Unit',
            $item->planningItem?->name ?? 'Item'
        ), ['url' => route('work-orders.show', $item->workOrder), 'work_order_id' => $item->work_order_id, 'work_order_item_id' => $item->id], $item->workOrder->site_id);
    }

    public function taskSubmitted(WorkOrderItem $item, string $action): void
    {
        $item->loadMissing(['workOrder.unit', 'planningItem']);

        $this->notifyRoles([UserRole::SpvHo], 'task_submitted', 'Task menunggu approval', sprintf(
            '%s - %s diajukan untuk %s.',
            $item->workOrder->unit?->current_plate ?? 'Unit',
            $item->planningItem?->name ?? 'Item',
            ucfirst($action)
        ), ['url' => route('work-orders.show', $item->workOrder), 'work_order_id' => $item->work_order_id, 'work_order_item_id' => $item->id, 'action' => $action]);
    }

    public function taskCreationRequested(WorkOrderItem $item): void
    {
        $item->loadMissing(['workOrder.unit', 'planningItem']);

        $this->notifyRoles([UserRole::SpvHo], 'task_creation_requested', 'Task menunggu approval', sprintf(
            '%s - %s diajukan untuk dibuat sekarang.',
            $item->workOrder->unit?->current_plate ?? 'Unit',
            $item->planningItem?->name ?? 'Item'
        ), ['url' => route('work-orders.show', $item->workOrder), 'work_order_id' => $item->work_order_id, 'work_order_item_id' => $item->id, 'action' => 'create_task']);
    }

    public function replaceApprovedForLogistics(WorkOrder $workOrder, WorkOrderItem $item): void
    {
        $workOrder->loadMissing('unit');

        if ($workOrder->unit?->is_warranty) {
            return;
        }

        $item->loadMissing('planningItem');

        $this->notifyRoles([UserRole::SpvHo], 'work_order_approved', 'WO disetujui untuk Spv HO', sprintf(
            'WO #%d %s - %s sudah disetujui dan membutuhkan koordinasi part.',
            $workOrder->id,
            $workOrder->unit?->current_plate,
            $item->planningItem?->name
        ), ['url' => route('work-orders.show', $workOrder), 'work_order_id' => $workOrder->id, 'work_order_item_id' => $item->id]);
    }

    public function unitBreakdown(Unit $unit): void
    {
        $this->notifyRoles([UserRole::SpvHo], 'unit_breakdown', 'Unit Breakdown diinput', sprintf(
            '%s ditandai Breakdown dan perlu dipantau.',
            $unit->current_plate
        ), ['unit_id' => $unit->id]);
    }

    /**
     * @param  Collection<int, WorkOrderItem>  $items
     */
    public function maintenanceOverdue(Collection $items): void
    {
        /** @var WorkOrderItem $item */
        $item = $items->firstOrFail();
        $item->loadMissing(['workOrder.unit', 'workOrder.site', 'planningItem']);
        $overdueCount = $items->count();
        $message = $overdueCount > 1
            ? sprintf(
                '%s - %s sudah overdue (%d WO menunggu tindakan).',
                $item->workOrder->unit?->current_plate ?? 'Unit',
                $item->planningItem?->name ?? 'Item',
                $overdueCount
            )
            : sprintf(
                '%s - %s di %s sudah overdue.',
                $item->workOrder->unit?->current_plate ?? 'Unit',
                $item->planningItem?->name ?? 'Item',
                $item->workOrder->site?->name ?? 'site'
            );

        $this->notifyRoles([UserRole::SpvHo], 'maintenance_overdue', 'Item maintenance overdue', $message, [
            'url' => route('work-orders.show', $item->workOrder),
            'work_order_id' => $item->work_order_id,
            'work_order_item_ids' => $items->pluck('id')->values()->all(),
            'unit_id' => $item->workOrder->unit_id,
            'planning_item_id' => $item->planning_item_id,
            'overdue_count' => $overdueCount,
        ]);
    }

    public function highUsageSecondWindow(HighUsageFlag $flag): void
    {
        $flag->loadMissing(['unit', 'planningItem']);

        $this->notifyRoles([UserRole::PlannerArea, UserRole::SpvHo], 'high_usage_window_2', 'High Usage Window 2', sprintf(
            '%s - %s perlu input jadwal baru karena High Usage belum ditindaklanjuti.',
            $flag->unit?->current_plate ?? 'Unit',
            $flag->planningItem?->name ?? 'Item'
        ), [
            'url' => route('high-usage.index'),
            'unit_id' => $flag->unit_id,
            'planning_item_id' => $flag->planning_item_id,
            'high_usage_flag_id' => $flag->id,
        ], $flag->unit?->site_id);
    }

    /**
     * @param  array<int, UserRole>  $roles
     * @param  array<string, mixed>  $data
     */
    private function notifyRoles(array $roles, string $type, string $title, string $message, array $data, ?int $siteId = null): void
    {
        $roleValues = collect($roles)->map(fn (UserRole $role): string => $role->value)->unique()->values()->all();

        User::query()
            ->whereIn('role', $roleValues)
            ->when($siteId !== null, fn (Builder $query) => $query->where(function (Builder $siteQuery) use ($siteId): void {
                $siteQuery->whereNull('site_id')->orWhere('site_id', $siteId);
            }))
            ->get()
            ->each(function (User $user) use ($type, $title, $message, $data): void {
                $exists = Notification::query()
                    ->where('user_id', $user->id)
                    ->where('type', $type)
                    ->when(isset($data['work_order_item_id']), fn (Builder $query) => $query->where('data->work_order_item_id', $data['work_order_item_id']))
                    ->when(isset($data['unit_id']), fn (Builder $query) => $query->where('data->unit_id', $data['unit_id']))
                    ->when(isset($data['planning_item_id']), fn (Builder $query) => $query->where('data->planning_item_id', $data['planning_item_id']))
                    ->whereNull('read_at')
                    ->exists();

                if ($exists) {
                    return;
                }

                Notification::query()->create([
                    'user_id' => $user->id,
                    'type' => $type,
                    'title' => $title,
                    'message' => $message,
                    'data' => $data,
                ]);
            });
    }
}
