<?php

namespace App\Services;

use App\Enums\UserRole;
use App\Models\HighUsageFlag;
use App\Models\Notification;
use App\Models\Site;
use App\Models\SystemThreshold;
use App\Models\Unit;
use App\Models\UnitSiteTransfer;
use App\Models\User;
use App\Models\WorkOrder;
use App\Models\WorkOrderItem;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Collection;

class FleetNotificationService
{
    public function __construct(private KmInputTrendService $kmInputTrendService) {}

    public function taskAutoGenerated(WorkOrderItem $item): void
    {
        $item->loadMissing(['workOrder.unit', 'planningItem']);

        $this->notifyRoles([UserRole::PlannerArea], 'task_auto_generated', 'Task maintenance baru', sprintf(
            '%s - %s masuk On Hold dan perlu ditindaklanjuti.',
            $item->workOrder->unit?->current_plate ?? 'Unit',
            $item->planningItem?->name ?? 'Item'
        ), ['url' => route('work-orders.show', $item->workOrder), 'work_order_id' => $item->work_order_id, 'work_order_item_id' => $item->id], $item->workOrder->site_id);
    }

    public function taskSubmitted(WorkOrderItem $item, string $action): void
    {
        $item->loadMissing(['workOrder.unit', 'planningItem']);

        $this->notifyRoles([UserRole::SpvHo], 'task_submitted', 'Task menunggu approval', sprintf(
            '%s - %s diajukan untuk %s.',
            $item->workOrder->unit?->current_plate ?? 'Unit',
            $item->planningItem?->name ?? 'Item',
            ucfirst($action)
        ), ['url' => route('work-orders.show', $item->workOrder), 'work_order_id' => $item->work_order_id, 'work_order_item_id' => $item->id, 'action' => $action]);
    }

    public function taskCreationRequested(WorkOrderItem $item): void
    {
        $item->loadMissing(['workOrder.unit', 'planningItem']);

        $this->notifyRoles([UserRole::SpvHo], 'task_creation_requested', 'Task menunggu approval', sprintf(
            '%s - %s diajukan untuk dibuat sekarang.',
            $item->workOrder->unit?->current_plate ?? 'Unit',
            $item->planningItem?->name ?? 'Item'
        ), ['url' => route('work-orders.show', $item->workOrder), 'work_order_id' => $item->work_order_id, 'work_order_item_id' => $item->id, 'action' => 'create_task']);
    }

    public function replaceApprovedForLogistics(WorkOrder $workOrder, WorkOrderItem $item): void
    {
        $workOrder->loadMissing('unit');

        if ($workOrder->unit?->is_warranty) {
            return;
        }

        $item->loadMissing('planningItem');

        $this->notifyRoles([UserRole::SpvHo], 'work_order_approved', 'WO disetujui untuk Spv HO', sprintf(
            'WO #%d %s - %s sudah disetujui dan membutuhkan koordinasi part.',
            $workOrder->id,
            $workOrder->unit?->current_plate,
            $item->planningItem?->name
        ), ['url' => route('work-orders.show', $workOrder), 'work_order_id' => $workOrder->id, 'work_order_item_id' => $item->id]);
    }

    public function workOrderItemCompleted(WorkOrderItem $item): void
    {
        $item->loadMissing(['workOrder.unit', 'planningItem']);

        $this->notifyRoles([UserRole::PlannerArea], 'work_order_item_completed', 'Item maintenance selesai', sprintf(
            '%s - %s selesai pada %s di KM %s.',
            $item->workOrder->unit?->current_plate ?? 'Unit',
            $item->planningItem?->name ?? 'Item',
            $item->completed_date?->toDateString() ?? '-',
            number_format((int) $item->completed_odo, 0, ',', '.')
        ), [
            'url' => route('work-orders.show', $item->workOrder),
            'work_order_id' => $item->work_order_id,
            'work_order_item_id' => $item->id,
            'unit_id' => $item->workOrder->unit_id,
            'planning_item_id' => $item->planning_item_id,
            'completed_date' => $item->completed_date?->toDateString(),
            'completed_odo' => $item->completed_odo,
        ], $item->workOrder->site_id);
    }

    public function unitBreakdown(Unit $unit): void
    {
        $this->notifyRoles([UserRole::SpvHo], 'unit_breakdown', 'Unit Breakdown diinput', sprintf(
            '%s ditandai Breakdown dan perlu dipantau.',
            $unit->current_plate
        ), ['unit_id' => $unit->id]);
    }

    public function unitSiteTransferRequested(UnitSiteTransfer $transfer): void
    {
        $transfer->loadMissing(['unit', 'fromSite', 'toSite']);

        $this->notifyRoles([UserRole::SpvHo], 'unit_site_transfer_requested', 'Pindah Site menunggu approval', sprintf(
            '%s diajukan pindah dari %s ke %s.',
            $transfer->unit?->current_plate ?? 'Unit',
            $transfer->fromSite?->name ?? '-',
            $transfer->toSite?->name ?? '-'
        ), [
            'url' => route('units.history', $transfer->unit_id),
            'unit_id' => $transfer->unit_id,
            'unit_site_transfer_id' => $transfer->id,
        ]);
    }

    public function unitSiteTransferApproved(UnitSiteTransfer $transfer, int $oldSiteId, int $newSiteId): void
    {
        $transfer->loadMissing(['unit', 'fromSite', 'toSite']);

        $data = [
            'url' => route('units.history', $transfer->unit_id),
            'unit_id' => $transfer->unit_id,
            'unit_site_transfer_id' => $transfer->id,
        ];

        $this->notifyRoles([UserRole::PlannerArea], 'unit_site_transfer_approved_old_region', 'Unit pindah site', sprintf(
            '%s sudah dipindah dari %s ke %s dan tidak lagi masuk scope area lama.',
            $transfer->unit?->current_plate ?? 'Unit',
            $transfer->fromSite?->name ?? '-',
            $transfer->toSite?->name ?? '-'
        ), $data, $oldSiteId);

        $this->notifyRoles([UserRole::PlannerArea], 'unit_site_transfer_approved_new_region', 'Unit baru masuk area', sprintf(
            '%s sudah masuk ke %s. WO aktif ikut berpindah scope.',
            $transfer->unit?->current_plate ?? 'Unit',
            $transfer->toSite?->name ?? '-'
        ), $data, $newSiteId);
    }

    /**
     * @param  Collection<int, WorkOrderItem>  $items
     */
    public function maintenanceOverdue(Collection $items): void
    {
        /** @var WorkOrderItem $item */
        $item = $items->firstOrFail();
        $item->loadMissing(['workOrder.unit', 'workOrder.site', 'planningItem']);
        $overdueCount = $items->count();
        $message = $overdueCount > 1
            ? sprintf(
                '%s - %s sudah overdue (%d WO menunggu tindakan).',
                $item->workOrder->unit?->current_plate ?? 'Unit',
                $item->planningItem?->name ?? 'Item',
                $overdueCount
            )
            : sprintf(
                '%s - %s di %s sudah overdue.',
                $item->workOrder->unit?->current_plate ?? 'Unit',
                $item->planningItem?->name ?? 'Item',
                $item->workOrder->site?->name ?? 'site'
            );

        $this->notifyRoles([UserRole::SpvHo], 'maintenance_overdue', 'Item maintenance overdue', $message, [
            'url' => route('work-orders.show', $item->workOrder),
            'work_order_id' => $item->work_order_id,
            'work_order_item_ids' => $items->pluck('id')->values()->all(),
            'unit_id' => $item->workOrder->unit_id,
            'planning_item_id' => $item->planning_item_id,
            'overdue_count' => $overdueCount,
        ]);
    }

    public function highUsageSecondWindow(HighUsageFlag $flag): void
    {
        $flag->loadMissing(['unit', 'planningItem']);

        $this->notifyRoles([UserRole::PlannerArea, UserRole::SpvHo], 'high_usage_window_2', 'High Usage Window 2', sprintf(
            '%s - %s perlu input jadwal baru karena High Usage belum ditindaklanjuti.',
            $flag->unit?->current_plate ?? 'Unit',
            $flag->planningItem?->name ?? 'Item'
        ), [
            'url' => route('high-usage.index'),
            'unit_id' => $flag->unit_id,
            'planning_item_id' => $flag->planning_item_id,
            'high_usage_flag_id' => $flag->id,
        ], $flag->unit?->site_id);
    }

    public function sendKmInputPeriodicSummaries(?CarbonImmutable $now = null): int
    {
        $now ??= CarbonImmutable::now();
        $intervalDays = $this->kmInputSummaryIntervalDays();
        $sentCount = 0;

        User::query()
            ->whereIn('role', [UserRole::PlannerArea->value, UserRole::SpvHo->value])
            ->with(['area:id,name', 'site:id,name'])
            ->get()
            ->each(function (User $user) use ($now, $intervalDays, &$sentCount): void {
                if (! $this->kmInputSummaryIsDue($user, $now, $intervalDays)) {
                    return;
                }

                $siteIds = $this->kmInputSummarySiteIds($user);

                if ($user->hasRole(UserRole::PlannerArea) && $siteIds === []) {
                    return;
                }

                $summary = $this->kmInputTrendService->summarize(
                    $siteIds,
                    KmInputTrendService::SUMMARY_DAYS,
                    $now->startOfDay()
                );
                $comparison = $summary['this_week_vs_last_week'];

                Notification::query()->create([
                    'user_id' => $user->id,
                    'type' => KmInputTrendService::NOTIFICATION_TYPE,
                    'title' => 'Ringkasan Input KM 7 Hari',
                    'message' => $this->kmInputSummaryMessage($user, $summary),
                    'data' => [
                        'url' => route('dashboard', ['km_trend_days' => KmInputTrendService::SUMMARY_DAYS]),
                        'scope' => $this->kmInputScopeLabel($user),
                        'period_start' => $summary['period_start'],
                        'period_end' => $summary['period_end'],
                        'daily_totals' => $summary['series'],
                        'current_total' => $comparison['current'],
                        'previous_total' => $comparison['previous'],
                        'delta' => $comparison['delta'],
                        'percentage_change' => $comparison['percentage_change'],
                    ],
                ]);

                $sentCount++;
            });

        return $sentCount;
    }

    private function kmInputSummaryIntervalDays(): int
    {
        $configuredValue = (int) SystemThreshold::query()
            ->where('key', KmInputTrendService::SUMMARY_INTERVAL_KEY)
            ->value('value');

        return max(1, $configuredValue ?: KmInputTrendService::DEFAULT_SUMMARY_INTERVAL_DAYS);
    }

    private function kmInputSummaryIsDue(User $user, CarbonImmutable $now, int $intervalDays): bool
    {
        $lastSentAt = Notification::query()
            ->where('user_id', $user->id)
            ->where('type', KmInputTrendService::NOTIFICATION_TYPE)
            ->latest('created_at')
            ->value('created_at');

        return $lastSentAt === null
            || CarbonImmutable::parse($lastSentAt)->addDays($intervalDays)->lessThanOrEqualTo($now);
    }

    /**
     * @return array<int, int>|null
     */
    private function kmInputSummarySiteIds(User $user): ?array
    {
        if ($user->hasRole(UserRole::SpvHo)) {
            return null;
        }

        return Site::query()
            ->when(
                $user->region_id !== null,
                fn (Builder $query) => $query->where('region_id', $user->region_id),
                fn (Builder $query) => $query->whereKey($user->site_id)
            )
            ->pluck('id')
            ->map(fn (mixed $siteId): int => (int) $siteId)
            ->all();
    }

    /**
     * @param  array<string, mixed>  $summary
     */
    private function kmInputSummaryMessage(User $user, array $summary): string
    {
        $dailyTotals = collect($summary['series'])
            ->map(fn (array $day): string => sprintf('%s: %d', $day['short_label'], $day['count']))
            ->implode('; ');
        $comparison = $summary['this_week_vs_last_week'];

        return sprintf(
            '%s. Total harian: %s. Total 7 hari berjalan %d input, dibanding 7 hari sebelumnya %d input (%s).',
            $this->kmInputScopeLabel($user),
            $dailyTotals,
            $comparison['current'],
            $comparison['previous'],
            $this->kmInputComparisonLabel($comparison)
        );
    }

    private function kmInputScopeLabel(User $user): string
    {
        if ($user->hasRole(UserRole::SpvHo)) {
            return 'Cakupan semua region';
        }

        if ($user->area !== null) {
            return 'Cakupan region '.$user->area->name;
        }

        return 'Cakupan site '.($user->site?->name ?? '-');
    }

    /**
     * @param  array{current: int, previous: int, delta: int, percentage_change: float|null}  $comparison
     */
    private function kmInputComparisonLabel(array $comparison): string
    {
        if ($comparison['delta'] === 0) {
            return 'tetap, selisih 0 input';
        }

        $direction = $comparison['delta'] > 0 ? 'naik' : 'turun';
        $label = sprintf('%s %d input', $direction, abs($comparison['delta']));

        if ($comparison['percentage_change'] === null) {
            return $label.', persentase tidak tersedia karena periode sebelumnya 0';
        }

        return sprintf('%s, perubahan %s%%', $label, number_format(abs($comparison['percentage_change']), 1, ',', '.'));
    }

    /**
     * @param  array<int, UserRole>  $roles
     * @param  array<string, mixed>  $data
     */
    private function notifyRoles(array $roles, string $type, string $title, string $message, array $data, ?int $siteId = null): void
    {
        $roleValues = collect($roles)->map(fn (UserRole $role): string => $role->value)->unique()->values()->all();
        $site = $siteId !== null ? Site::query()->find($siteId) : null;

        User::query()
            ->whereIn('role', $roleValues)
            ->when($siteId !== null, fn (Builder $query) => $query->where(function (Builder $siteQuery) use ($siteId, $site): void {
                $siteQuery
                    ->where(fn (Builder $roleQuery) => $roleQuery->where('role', '!=', UserRole::PlannerArea->value)->where(fn (Builder $scopeQuery) => $scopeQuery->whereNull('site_id')->orWhere('site_id', $siteId)))
                    ->orWhere(fn (Builder $roleQuery) => $roleQuery->where('role', UserRole::PlannerArea->value)->where(function (Builder $plannerQuery) use ($siteId, $site): void {
                        $plannerQuery->where('site_id', $siteId);

                        if ($site?->region_id !== null) {
                            $plannerQuery->orWhere('region_id', $site->region_id);
                        }
                    }));
            }))
            ->get()
            ->each(function (User $user) use ($type, $title, $message, $data): void {
                $exists = Notification::query()
                    ->where('user_id', $user->id)
                    ->where('type', $type)
                    ->when(isset($data['unit_site_transfer_id']), fn (Builder $query) => $query->where('data->unit_site_transfer_id', $data['unit_site_transfer_id']))
                    ->when($type === 'work_order_item_completed' && isset($data['work_order_id']), fn (Builder $query) => $query->where('data->work_order_id', $data['work_order_id']))
                    ->when($type !== 'work_order_item_completed' && isset($data['work_order_item_id']), fn (Builder $query) => $query->where('data->work_order_item_id', $data['work_order_item_id']))
                    ->when(isset($data['unit_id']), fn (Builder $query) => $query->where('data->unit_id', $data['unit_id']))
                    ->when($type !== 'work_order_item_completed' && isset($data['planning_item_id']), fn (Builder $query) => $query->where('data->planning_item_id', $data['planning_item_id']))
                    ->whereNull('read_at')
                    ->exists();

                if ($exists) {
                    return;
                }

                Notification::query()->create([
                    'user_id' => $user->id,
                    'type' => $type,
                    'title' => $title,
                    'message' => $message,
                    'data' => $data,
                ]);
            });
    }
}
