<?php

namespace App\Services;

use App\Models\SystemThreshold;
use App\Models\Unit;
use App\Models\UnitPlanning;
use App\Models\WorkOrder;
use App\Models\WorkOrderItem;
use App\Support\WorkOrderMerger;
use Carbon\CarbonImmutable;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;

class MaintenanceTriggerService
{
    public function __construct(private WorkOrderProgressService $workOrderProgressService) {}

    /**
     * @param  array<int, int>  $skipUnitPlanningIds
     * @return array<int, WorkOrderItem>
     */
    public function checkAndTrigger(Unit $unit, array $skipUnitPlanningIds = []): array
    {
        return DB::transaction(function () use ($unit, $skipUnitPlanningIds): array {
            $unit->loadMissing('unitPlannings.planningItem');

            $warningKm = $this->thresholdValue('warning_km', 500);
            $warningDays = $this->thresholdValue('warning_days', 7);
            $today = CarbonImmutable::today();

            $triggeredPlannings = $unit->unitPlannings
                ->where('is_excluded', false)
                ->reject(fn (UnitPlanning $unitPlanning): bool => $unitPlanning->isBaselineMissing())
                ->filter(fn (UnitPlanning $unitPlanning): bool => $this->isDueSoon($unit, $unitPlanning, $warningKm, $warningDays, $today))
                ->reject(fn (UnitPlanning $unitPlanning): bool => in_array($unitPlanning->id, $skipUnitPlanningIds, true))
                ->reject(fn (UnitPlanning $unitPlanning): bool => $this->hasActiveItem($unitPlanning))
                ->values();

            if ($triggeredPlannings->isEmpty()) {
                return [];
            }

            $replacementPlanningIds = $this->replacementPlanningIds($triggeredPlannings);
            $this->syncSupersededWorkOrders($replacementPlanningIds);

            $replacementPlannings = $triggeredPlannings
                ->filter(fn (UnitPlanning $unitPlanning): bool => $replacementPlanningIds->contains($unitPlanning->id))
                ->values();
            $normalPlannings = $triggeredPlannings
                ->reject(fn (UnitPlanning $unitPlanning): bool => $replacementPlanningIds->contains($unitPlanning->id))
                ->values();

            $createdItems = collect();

            if ($replacementPlannings->isNotEmpty()) {
                $createdItems->push(...$this->createItems($unit, $replacementPlannings, true));
            }

            if ($normalPlannings->isNotEmpty()) {
                $createdItems->push(...$this->createItems($unit, $normalPlannings));
            }

            return $createdItems->all();
        });
    }

    /**
     * @param  Collection<int, UnitPlanning>  $unitPlannings
     * @return array<int, WorkOrderItem>
     */
    private function createItems(Unit $unit, Collection $unitPlannings, bool $forceNewWorkOrder = false): array
    {
        $workOrder = $forceNewWorkOrder ? null : WorkOrderMerger::openWorkOrderFor($unit->id);

        if (! $workOrder) {
            $workOrder = WorkOrder::query()->create([
                'unit_id' => $unit->id,
                'site_id' => $unit->site_id,
                'trigger_type' => 'normal',
                'status' => 'open',
            ]);
        }

        return $unitPlannings
            ->map(fn (UnitPlanning $unitPlanning): WorkOrderItem => WorkOrderItem::query()->create([
                'work_order_id' => $workOrder->id,
                'unit_planning_id' => $unitPlanning->id,
                'planning_item_id' => $unitPlanning->planning_item_id,
                'status' => 'on_hold',
            ]))
            ->each(fn (WorkOrderItem $item) => app(FleetNotificationService::class)->taskAutoGenerated($item))
            ->all();
    }

    /**
     * @param  Collection<int, UnitPlanning>  $unitPlannings
     * @return Collection<int, int>
     */
    private function replacementPlanningIds(Collection $unitPlannings): Collection
    {
        return WorkOrderItem::query()
            ->whereIn('unit_planning_id', $unitPlannings->pluck('id'))
            ->where('status', 'cancelled')
            ->whereHas('workOrder', fn ($query) => $query->whereNotIn('status', ['complete', 'cancelled']))
            ->pluck('unit_planning_id')
            ->unique()
            ->values();
    }

    /**
     * @param  Collection<int, int>  $unitPlanningIds
     */
    private function syncSupersededWorkOrders(Collection $unitPlanningIds): void
    {
        if ($unitPlanningIds->isEmpty()) {
            return;
        }

        WorkOrder::query()
            ->whereNotIn('status', ['complete', 'cancelled'])
            ->whereHas('items', fn ($query) => $query
                ->whereIn('unit_planning_id', $unitPlanningIds)
                ->where('status', 'cancelled'))
            ->lockForUpdate()
            ->get()
            ->each(fn (WorkOrder $workOrder) => $this->workOrderProgressService->sync($workOrder));
    }

    private function thresholdValue(string $key, int $default): int
    {
        return (int) (SystemThreshold::query()->where('key', $key)->value('value') ?? $default);
    }

    private function isDueSoon(Unit $unit, UnitPlanning $unitPlanning, int $warningKm, int $warningDays, CarbonImmutable $today): bool
    {
        if ($unitPlanning->isBaselineMissing()) {
            return false;
        }

        $isKmDueSoon = $unitPlanning->next_due_km !== null
            && $unit->current_odo >= ($unitPlanning->next_due_km - $warningKm);

        $isDateDueSoon = $unitPlanning->next_due_date !== null
            && $today->greaterThanOrEqualTo(CarbonImmutable::parse($unitPlanning->next_due_date)->subDays($warningDays));

        return $isKmDueSoon || $isDateDueSoon;
    }

    private function hasActiveItem(UnitPlanning $unitPlanning): bool
    {
        return WorkOrderItem::query()
            ->where('unit_planning_id', $unitPlanning->id)
            ->whereNotIn('status', ['complete', 'postponed', 'rejected', 'cancelled'])
            ->exists();
    }
}
