import DangerButton from '@/Components/DangerButton';
import PaginationLinks from '@/Components/PaginationLinks';
import PrimaryButton from '@/Components/PrimaryButton';
import { Card, CardContent } from '@/Components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/Components/ui/table';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { PageProps, PaginatedCollection, User } from '@/types';
import { Head, Link, router } from '@inertiajs/react';

export default function Index({ auth, users }: PageProps<{ users: PaginatedCollection<User> }>) { const destroy = (user: User) => { if (confirm(`Hapus pengguna ${user.name}?`)) router.delete(route('users.destroy', user.id)); }; return <AuthenticatedLayout header={<h2 className="text-xl font-semibold leading-tight text-foreground">Manajemen Pengguna</h2>}><Head title="Manajemen Pengguna" /><div className="py-10"><div className="mx-auto max-w-7xl space-y-6 sm:px-6 lg:px-8"><Link href={route('users.create')}><PrimaryButton>Tambah Pengguna</PrimaryButton></Link><Card><CardContent><div className="overflow-x-auto"><Table><TableHeader><TableRow>{['Nama','Email','Peran','Region','Lokasi','Aksi'].map((head) => <TableHead key={head}>{head}</TableHead>)}</TableRow></TableHeader><TableBody>{users.data.map((user) => <TableRow key={user.id}><TableCell className="font-medium text-foreground">{user.name}</TableCell><TableCell>{user.email}</TableCell><TableCell>{{ superadmin: 'Superadmin', mekanik: 'Mekanik', planner_area: 'Planner Area', spv_ho: 'Spv HO' }[user.role] ?? user.role}</TableCell><TableCell>{user.area?.name ?? '-'}</TableCell><TableCell>{user.site?.name ?? '-'}</TableCell><TableCell><div className="flex flex-wrap gap-2"><Link className="text-sm font-medium text-primary hover:underline" href={route('users.edit', user.id)}>Edit</Link>{auth.user.id !== user.id && <DangerButton onClick={() => destroy(user)}>Hapus</DangerButton>}</div></TableCell></TableRow>)}</TableBody></Table></div><PaginationLinks meta={users.meta} /></CardContent></Card></div></div></AuthenticatedLayout>; }
