import ConfirmDialog from '@/Components/ConfirmDialog';
import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import TextInput from '@/Components/TextInput';
import { Card, CardContent } from '@/Components/ui/card';
import { SystemThreshold } from '@/types';
import { Link, useForm } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

export default function Form({ systemThreshold }: { systemThreshold?: SystemThreshold }) { const form = useForm({ key: systemThreshold?.key ?? '', value: systemThreshold?.value ?? '', description: systemThreshold?.description ?? '' }); const [showConfirm, setShowConfirm] = useState(false); const submit = (event: FormEvent) => { event.preventDefault(); setShowConfirm(true); }; const confirm = () => { systemThreshold ? form.patch(route('system-thresholds.update', systemThreshold.id), { onFinish: () => setShowConfirm(false) }) : form.post(route('system-thresholds.store'), { onFinish: () => setShowConfirm(false) }); }; return <><Card><CardContent><form onSubmit={submit} className="space-y-6"><div className="space-y-2"><InputLabel htmlFor="key" value="Kode Pengaturan" /><TextInput id="key" className="block w-full" value={form.data.key} onChange={(e) => form.setData('key', e.target.value)} required /><InputError message={form.errors.key} /></div><div className="space-y-2"><InputLabel htmlFor="value" value="Nilai" /><TextInput id="value" className="block w-full" value={form.data.value} onChange={(e) => form.setData('value', e.target.value)} required /><InputError message={form.errors.value} /></div><div className="space-y-2"><InputLabel htmlFor="description" value="Keterangan" /><TextInput id="description" className="block w-full" value={form.data.description ?? ''} onChange={(e) => form.setData('description', e.target.value)} /><InputError message={form.errors.description} /></div><div className="flex items-center gap-3"><PrimaryButton disabled={form.processing}>Simpan</PrimaryButton><Link href={route('system-thresholds.index')} className="text-sm text-muted-foreground hover:text-foreground">Batal</Link></div></form></CardContent></Card><ConfirmDialog show={showConfirm} message={`Simpan pengaturan ${form.data.key || '-'} dengan nilai ${form.data.value || '-'}?`} processing={form.processing} onCancel={() => setShowConfirm(false)} onConfirm={confirm} /></>; }
