import DangerButton from '@/Components/DangerButton';
import PaginationLinks from '@/Components/PaginationLinks';
import PrimaryButton from '@/Components/PrimaryButton';
import { Card, CardContent } from '@/Components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/Components/ui/table';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { PageProps, PaginatedCollection, SystemThreshold } from '@/types';
import { Head, Link, router } from '@inertiajs/react';

export default function Index({ auth, systemThresholds }: PageProps<{ systemThresholds: PaginatedCollection<SystemThreshold> }>) { const destroy = (threshold: SystemThreshold) => { if (confirm(`Delete ${threshold.key}?`)) router.delete(route('system-thresholds.destroy', threshold.id)); }; return <AuthenticatedLayout header={<h2 className="text-xl font-semibold leading-tight text-foreground">System Thresholds</h2>}><Head title="System Thresholds" /><div className="py-10"><div className="mx-auto max-w-7xl space-y-6 sm:px-6 lg:px-8"><Link href={route('system-thresholds.create')}><PrimaryButton>Add Threshold</PrimaryButton></Link><Card><CardContent><div className="overflow-x-auto"><Table><TableHeader><TableRow>{['Key','Value','Description','Updated By','Actions'].map((head) => <TableHead key={head}>{head}</TableHead>)}</TableRow></TableHeader><TableBody>{systemThresholds.data.map((threshold) => <TableRow key={threshold.id}><TableCell className="font-medium text-foreground">{threshold.key}</TableCell><TableCell>{threshold.value}</TableCell><TableCell>{threshold.description}</TableCell><TableCell>{threshold.updated_by?.name ?? '-'}</TableCell><TableCell><div className="flex flex-wrap gap-2"><Link className="text-sm font-medium text-primary hover:underline" href={route('system-thresholds.edit', threshold.id)}>Edit</Link><DangerButton onClick={() => destroy(threshold)}>Delete</DangerButton></div></TableCell></TableRow>)}</TableBody></Table></div><PaginationLinks meta={systemThresholds.meta} /></CardContent></Card></div></div></AuthenticatedLayout>; }
